# Student Name	: Ee En Goh
# Student Number: 17202691
# Student Email : ee.goh@ucdconnect.ie
# Version	: 1.0

CC = gcc
CFLAGS = -Wall -pthread --std=c99

all : 
	$(CC) $(CFLAGS) master.c -o master
	$(CC) $(CFLAGS) worker.c -o worker
	
clean :
	$(RM) master worker *.o *~

